# references
# https://www.w3schools.com/python/python_ref_functions.asp
# https://docs.python.org/3/library/functions.html
# 
#import _03lambdas
import os
def test():
    """
    This is a short description of the functionality in this method
    it doesn't do anything.
    >>> test()

    """
    pass

# 40 - 16 = 24
funclist:[str] = ['__bool__', 
                  '__class__', 
                  '__delattr__', 
                  '__dir__', 
                  '__doc__', 
                  '__eq__', 
                  '__format__', 
                  '__ge__', 
                  '__getattribute__', 
                  '__getstate__', 
                  '__gt__', 
                  '__hash__', 
                  '__init__', 
                  '__init_subclass__', 
                  '__le__', 
                  '__lt__', 
                  '__ne__', 
                  '__new__', 
                  '__reduce__', 
                  '__reduce_ex__', 
                  '__repr__', 
                  '__setattr__', 
                  '__sizeof__', 
                  '__str__', 
                  '__subclasshook__']


class Animal:
    pass

# 72 - 46 = 26
classlist:[str] = ['__class__', 
                   '__delattr__', 
                   '__dict__', 
                   '__dir__', 
                   '__doc__', 
                   '__eq__', 
                   '__format__', 
                   '__ge__', 
                   '__getattribute__', 
                   '__getstate__', 
                   '__gt__', 
                   '__hash__', 
                   '__init__', 
                   '__init_subclass__', 
                   '__le__', 
                   '__lt__', 
                   '__module__', 
                   '__ne__', 
                   '__new__', 
                   '__reduce__', 
                   '__reduce_ex__', 
                   '__repr__', 
                   '__setattr__', 
                   '__sizeof__', 
                   '__str__', 
                   '__subclasshook__', 
                   '__weakref__']

# 84 -74 = 10
modulelist:[str] = ['__builtins__', 
                    '__cached__', 
                    '__doc__', 
                    '__file__', 
                    '__loader__', 
                    '__name__', 
                    '__package__', 
                    '__spec__', 
                    'multiply_values', 
                    'sum_three_values', 
                    'sum_two_values']
#245-86 = 159
listOs:[str] = ['DirEntry', 
                'EX_OK', 
                'F_OK', 
                'GenericAlias', 
                'Mapping', 
                'MutableMapping', 
                'O_APPEND', 
                'O_BINARY', 
                'O_CREAT', 
                'O_EXCL', 
                'O_NOINHERIT', 
                'O_RANDOM', 
                'O_RDONLY', 
                'O_RDWR', 
                'O_SEQUENTIAL', 
                'O_SHORT_LIVED', 
                'O_TEMPORARY', 
                'O_TEXT', 
                'O_TRUNC', 
                'O_WRONLY', 
                'P_DETACH', 
                'P_NOWAIT', 
                'P_NOWAITO', 
                'P_OVERLAY', 
                'P_WAIT', 
                'PathLike', 
                'R_OK', 
                'SEEK_CUR', 
                'SEEK_END', 
                'SEEK_SET', 
                'TMP_MAX', 
                'W_OK', 
                'X_OK', 
                '_AddedDllDirectory', 
                '_Environ', 
                '__all__', 
                '__builtins__', 
                '__doc__', 
                '__file__', 
                '__loader__', 
                '__name__', 
                '__package__', 
                '__spec__', 
                '_check_methods', 
                '_execvpe', 
                '_exists', 
                '_exit', 
                '_fspath', 
                '_get_exports_list', 
                '_wrap_close', 
                'abc', 
                'abort', 
                'access', 
                'add_dll_directory', 
                'altsep', 
                'chdir', 
                'chmod', 
                'close', 
                'closerange', 
                'cpu_count', 
                'curdir', 
                'defpath', 
                'device_encoding', 
                'devnull', 
                'dup', 
                'dup2', 
                'environ', 
                'error', 
                'execl', 
                'execle', 
                'execlp', 
                'execlpe', 
                'execv', 
                'execve', 
                'execvp', 
                'execvpe', 
                'extsep', 
                'fdopen', 
                'fsdecode', 
                'fsencode', 
                'fspath', 
                'fstat', 
                'fsync', 
                'ftruncate', 
                'get_blocking', 
                'get_exec_path', 
                'get_handle_inheritable', 
                'get_inheritable', 
                'get_terminal_size', 
                'getcwd', 
                'getcwdb', 
                'getenv', 
                'getlogin', 
                'getpid', 
                'getppid', 
                'isatty', 
                'kill', 
                'linesep', 
                'link', 
                'listdir', 
                'listdrives', 
                'listmounts', 
                'listvolumes', 
                'lseek', 
                'lstat', 
                'makedirs', 
                'mkdir', 
                'name', 
                'open', 
                'pardir', 
                'path', 
                'pathsep', 
                'pipe', 
                'popen', 
                'putenv', 
                'read', 
                'readlink', 
                'remove', 
                'removedirs', 
                'rename', 
                'renames', 
                'replace', 
                'rmdir', 
                'scandir', 
                'sep', 
                'set_blocking', 
                'set_handle_inheritable', 
                'set_inheritable', 
                'spawnl', 
                'spawnle', 
                'spawnv', 
                'spawnve', 
                'st', 
                'startfile', 
                'stat', 
                'stat_result', 
                'statvfs_result', 
                'strerror', 
                'supports_bytes_environ', 
                'supports_dir_fd', 
                'supports_effective_ids', 
                'supports_fd', 
                'supports_follow_symlinks', 
                'symlink', 
                'sys', 
                'system', 
                'terminal_size', 
                'times', 
                'times_result', 
                'truncate', 
                'umask', 
                'uname_result', 
                'unlink', 
                'unsetenv', 
                'urandom', 
                'utime', 
                'waitpid', 
                'waitstatus_to_exitcode', 
                'walk', 
                'write']
#print(dir(test()))
#print(test.__doc__)

#print(dir(Animal()))
#print(dir(_03lambdas))
print(dir(os))